### ISSUE TITLE
Get rid of strings in OfType iterator

### ISSUE THREAD

**Issue by rponudic** [fusonic/linq#13]
If you currently use the ```ofType``` iterator you have to look up what you can pass in as the actual type you want to be filtered:

```php
Linq::from($array)->ofType('bool')  // or was that boolean? double vs float? 
```

As to my knowledge there isn't any built-in type enum we could create our own to prevent the user from having to look inside the ```OfTypeIterator``` to find out what he has to pass as argument:

```php
Linq::from($array)->ofType(Type::string)
```

**Comment by davidroth** [comment]
I basically like the idea but I am concerned about the discoverability of these Type class.
How does the user know that this additional Type class exists?

**Comment by mburtscher** [comment]
Luckily you don't have to worry about this when working with objects since PHP 5.5 where you can use the new `::class` constant:

http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by davidroth** [comment]
@mburtscher :+1:
