### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by robations** [fusonic/linq#18]
Love the ability to do this stuff in PHP, especially after using libraries like RxJS and lodash in node-land. However I've run into a situation that wasn't quite as I expected. I was hoping to use Linq to process thousands of DB rows in bulk, something like this:

```
Linq::from($rowIterator)
    ->where(function ($x) { return $x[0]->hasBananas(); })
    ->select(function ($x) { return $x[0]; })
    ->chunk(2)       // <-- tiny chunk size for this example
    ->each(function (Linq $chunk) {
        $chunk->... // do stuff
    })
;
```

I'm using Doctrine and batch processing in chunks helps keep things moving. When tracing the output, I was expecting to get something like:

```
(
  where
  select
  where
  select
  each
    do stuff
    do stuff
) repeat all until all rows finished
```

Whereas I actually get:

```
(
  where
  select
) repeat for total number of rows
(
  each
    do stuff
    do stuff
) repeat until all rows processed
```

This means that when processing thousands of rows, even though I'm using an iterator, they still all end up in memory at the same time.

**Comment by davidroth** [comment]
Your assumption is right. The current behavior is because the chunk implementation uses grouping which by nature needs to process all elements first: https://github.com/fusonic/linq/blob/master/src/Fusonic/Linq/Linq.php#L183

Using yield a better implementation withing an iterator could look like this:

```php
$chunk = [];
$current = 1;
foreach ($this as $d)
{
    $current++;
    $chunk[] = $d;

    if ($current >= $chunksize) {
        yield return $chunk;
        $chunk = [];
        $current = 0;
    }
}
```
I hope I will find some time soon to update this. Otherwise, a pull request would be greatly appreciated :)

**Comment by robations** [comment]
Thanks for your reply David. Happy to send through a pull request, though I'm away for a week from tomorrow, not sure how much I'll get done today.

I presume you're okay with the PHP requirement being bumped to 5.5 in order to use `yield`? Version 5.4 is now end-of-life in any case. Technically this would be a break in backwards compatibility so might require a major release.

**Comment by davidroth** [comment]
Yes you can use php 5.5 features. I already planned to create a new major release (2.0) which targets at least php 5.5.

I will branch the current 1.x version and master will then get the new 2.x baseline.
I am on vacation the next week,  so there is no hurry ;)

Anyway, thanks for your feedback and I am looking forward for your PR!
